### ISSUE TITLE
waline导入不进去

### ISSUE THREAD

**Issue by Dion-Lee** [chengzhongxue/plugin-comment-migrate#1]
<img width="1781" alt="image" src="https://github.com/user-attachments/assets/fdb20970-af69-45f8-9f20-193e4a7988d6">

**Comment by Dion-Lee** [comment]
大佬一定要帮助解决呀，现在用的waline，总数会有各种各样的小毛病

**Comment by chengzhongxue** [comment]
给日志，不然我也看不出什么毛病

**Comment by Dion-Lee** [comment]
> 给日志，不然我也看不出什么毛病

[halo-log-2024-08-13 10_24.log](https://github.com/user-attachments/files/16593696/halo-log-2024-08-13.10_24.log)

**Comment by Dion-Lee** [comment]
[halo-log-2024-08-13 10_24.log](https://github.com/user-attachments/files/16593694/halo-log-2024-08-13.10_24.log)

**Comment by chengzhongxue** [comment]
加我微信吧

**Comment by Dion-Lee** [comment]
> 加我微信吧
微信名程忠学？

**Comment by chengzhongxue** [comment]
OkayLoyalty
